name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: "^1.18"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up environment
      run: echo "GOVERSION=$(go version)" >> $GITHUB_ENV
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: build --snapshot --rm-dist
