name: Coverage
on:
  push:
    branches:
    - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: "^1.18"
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Configure git
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Calculate coverage
      run: |
        go test -v -covermode=count -coverprofile=coverage.out.raw -coverpkg=./... ./...
        grep -v mock_ coverage.out.raw > coverage.out
    - name: Set GOROOT
      run: |
        echo "GOROOT=$GOROOT_1_18_X64" >> $GITHUB_ENV
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.9
    - name: Coveralls
      uses: coverallsapp/github-action@v2.2.0
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
