name: Release

on:
  push:
    branches:
    - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: "^1.18"
    - name: Install ccv
      run: go install github.com/smlx/ccv@latest
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Configure Git
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Bump tag if necessary
      id: tag
      run: |
        if [ -z $(git tag -l $(ccv)) ]; then
          git tag $(ccv)
          git push --tags
          echo "::set-output name=new::true"
        fi
    - name: Set up environment
      run: echo "GOVERSION=$(go version)" >> $GITHUB_ENV
    - name: Run GoReleaser
      if: steps.tag.outputs.new == 'true'
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
