name: Test Suite
on: pull_request

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up go
      uses: actions/setup-go@v2
      with:
        go-version: "^1.18"
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Configure git
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Run tests
      run: go test -v .
